name: news_api
description: News API
version: 0.0.1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  json_annotation: ^4.8.1
  meta: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  melos: ^3.1.1
  test: ^1.24.4

